version: '2'
services:
  examples-db:
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_USER: arquisoft
        MYSQL_PASSWORD: 123
        MYSQL_DATABASE: examples
        MYSQL_HOST: examples-db
    image: mysql
    ports:
      - "3309:3306"
  examples-ms:
    environment:
        PORT: '4001'
    image: dafrodriguezro/2b_example
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4001 -b '0.0.0.0'"
    ports:
      - "4001:4001"
    depends_on:
        - examples-db
